name: trem
description: trem

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_background_service: ^2.1.3
  device_info_plus: ^4.0.0
  web_socket_channel: ^2.2.0
  audioplayers: ^1.0.1
  intl: ^0.17.0
  perfect_volume_control: ^1.0.5
  uuid: ^3.0.6
  hive_flutter: ^1.1.0
  hive: ^2.2.2
  firebase_messaging: ^11.4.2
  firebase_core: ^1.18.0
  loggy: ^2.0.1+1
  flutter_loggy: ^2.0.1
  http: ^0.13.4
  geolocator: ^8.2.1
  clipboard: ^0.1.3

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - audios/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
