name: trem_pocket
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  firebase_core: ^2.4.0
  firebase_messaging: ^14.2.0
  clipboard: ^0.1.3
  flutter_background_service: ^2.4.6
  flutter_local_notifications: ^13.0.0
  device_info_plus: ^8.0.0
  shared_preferences: ^2.0.15
  package_info_plus: ^3.0.2
  markdown_widget: ^1.3.0+2
  url_launcher: ^6.1.7
  flutter_switch: ^0.3.2
  store_checker: ^1.1.0
  alarmplayer: ^1.0.5
  auto_start_flutter: ^0.1.1
  android_autostart: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audios/